name: Doc Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Pip Install Requirements
        run: |
          python3 -m pip install pybind11 --user
          python3 -m pip install -r docs/requirements.txt --user

      - name: Install docreset
        run: |
          python3 setup.py install --user

      - name: DocTest
        run: |
          cd docs && make html_cn SPHINXOPTS="-W --keep-going"
          cd ../
          mkdir _site
          cp -r docs/build-cn/html/* ./_site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
