name: Document Release

on:
  push:
    branches:
      - master

jobs:
  API_Document_Release:
    name: API Document Release
    runs-on: ubuntu-18.04
    steps:
    - name: Build triggering
      env:
        API_TOKEN: ${{ secrets.READ_THE_DOCS_TOKEN }}
      run: |
        curl -X POST -H "Authorization: Token ${API_TOKEN}" https://readthedocs.org/api/v3/projects/oneflow-cn/versions/latest/builds/
